spring:
  application:
    name: eureka-provider
  zipkin:
    base-url: http://192.168.14.112:9411

server:
  port: 9091

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/