spring:
  application:
    name: eureka-rest-consumer
  zipkin:
    base-url: http://192.168.14.112:9411

server:
  port: 8081

ribbon:
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
