spring:
  application:
    name: eureka-fegin-consumer

server:
  port: 8080

ribbon:
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/